#!/bin/bash
#-------------------------------------------------------------------------------
# make_derived.sh -- regenerate the DERIVED placement fixtures.
#
#     ./make_derived.sh
#
# fixtures/*.out are captured from real Derecho runs and must stay that way.
# The files here are NOT captured: each is mechanically transformed from
# ../bound_mpich.out to produce a case we would otherwise need node hours -- and
# in some cases a misconfigured launcher -- to observe.  They live in their own
# directory and are regenerated by this script rather than hand-edited, so the
# distinction between "measured" and "constructed" can never blur.
#
#   perthread_mpich.out  every mask narrowed to ONE SMT sibling, header changed
#                        to OMP_PLACES=threads.  Must come out CLEAN: this is a
#                        good run under the other legal intent, and flagging it
#                        would make the whole `threads` half of the sweep
#                        unreadable.                            -> no rules
#
#   wholecore_mpich.out  the good run re-declared as OMP_PLACES=threads without
#                        narrowing anything: the masks are still whole cores.
#                        The mirror image of perthread_mpich.out, and the reason
#                        the mask rules compare against the DECLARED intent in
#                        both directions rather than just accepting anything
#                        narrow.                              -> wide_mask
#
#   smt256_mpich.out     both nodes' ranks folded onto ONE node, the second
#                        node's threads landing on the SMT siblings: 16 ranks x
#                        16 threads = 256 threads on 128 cores, deliberately.
#                        Two threads per core is what this geometry ASKED for,
#                        so nothing may fire -- which is only true because the
#                        occupancy threshold is ceil(threads/node / cores/node)
#                        rather than a hardcoded 1.  BenchmarkRunnerPlan.md
#                        section 6 calls this product out as the only way to put
#                        SMT siblings to work, and it is a different axis from
#                        OMP_PLACES.                            -> no rules
#
#   unbound_mpich.out    every mask widened to the whole node, as if the launcher
#                        had been given --cpu-bind none.       -> unpinned
#
#   splitmask_mpich.out  every mask is two CPUs on two DIFFERENT cores.  Two
#                        allowed CPUs is the right COUNT for OMP_PLACES=cores,
#                        so counting mask size is not enough -- only mapping the
#                        mask back to physical cores catches it.
#                                                              -> split_mask
#
#   offset_mpich.out     every rank shifted 4 cores up the node, so a 16-core
#                        rank covers three L3 groups instead of two, two NUMA
#                        domains instead of one, and -- for the rank that now
#                        sits across core 64 -- both sockets.  Nothing is
#                        oversubscribed and every mask is a clean whole core:
#                        the rank is simply in the wrong place, which is the only
#                        pathology the mask rules cannot see.  Rows past core 127
#                        are dropped rather than wrapped, since wrapping would
#                        collide with rank 0 and turn this into an
#                        oversubscription case.
#                       -> l3_straddle, numa_straddle, socket_straddle
#
# Between them these six cover every rule in placement_rules.sh except
# partial_core and oversubscription, which the two captured traps already cover.
#
# Derecho's core->group mapping, used to keep offset_mpich.out self-consistent
# with fixtures/topology.json:  socket = core/64,  numa = core/16,  l3 = core/8.
#-------------------------------------------------------------------------------
set -e
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
src="${HERE}/../bound_mpich.out"

[ -f "${src}" ] || { echo "missing ${src}" >&2; exit 1; }

#-------------------------------------------------------------------------------
# Each transform is expressed once, over both output formats.  The checker only
# reads the `csv:` rows, but a fixture whose human lines contradict its csv rows
# is a trap for the next reader, so both are rewritten.
#
# csv layout: rank,thread,nthreads,host,cpu,core,socket,numa,l3,place,nallowed,"affinity"
#-------------------------------------------------------------------------------
derive () {
    local dst="${HERE}/$1" mode="$2"
    awk -v mode="${mode}" -v stride=128 '
        function emit_csv (f, aff,   i, out) {
            out = f[1]
            for (i = 2; i <= 11; i++) out = out "," f[i]
            printf "csv: %s,\"%s\"\n", out, aff
        }
        # rewrite "key value" pairs on a human MPI rank line
        function set_field (key, val,   i) {
            for (i = 1; i <= NF; i++) if ($(i - 1) == key) $i = val
        }

        /^# env / {
            if (mode == "perthread" || mode == "wholecore")
                gsub(/OMP_PLACES=cores/, "OMP_PLACES=threads")
            if (mode == "unbound")   gsub(/OMP_PROC_BIND=spread/, "OMP_PROC_BIND=false")
            print; next
        }

        /^MPI rank / {
            for (i = 1; i <= NF; i++) if ($i == "core") c = $(i + 1) + 0
            if (mode == "perthread") {
                set_field("cpu", c); set_field("nallowed", 1); set_field("affinity", c)
            } else if (mode == "unbound") {
                set_field("nallowed", 2 * stride)
                set_field("affinity", "0-" (2 * stride - 1))
            } else if (mode == "splitmask") {
                set_field("affinity", c "," (c + 1))
            } else if (mode == "smt256") {
                if ($0 ~ /dec0154/) { sub(/dec0154/, "dec0153"); set_field("cpu", c + stride) }
            } else if (mode == "offset") {
                nc = c + 4
                if (nc > stride - 1) next
                set_field("cpu", nc);    set_field("core", nc)
                set_field("socket", int(nc / 64)); set_field("numa", int(nc / 16))
                set_field("l3", int(nc / 8))
                set_field("affinity", nc "," (nc + stride))
            }
            print; next
        }

        /^csv: [0-9]/ {
            if (mode == "wholecore") { print; next }   # header-only transform
            line = substr($0, 6)
            q = index(line, "\"")
            split(substr(line, 1, q - 1), f, ",")
            c = f[6] + 0

            if (mode == "perthread")      { f[5] = c;  f[11] = 1;          emit_csv(f, c) }
            else if (mode == "unbound")   { f[11] = 2 * stride;            emit_csv(f, "0-" (2 * stride - 1)) }
            else if (mode == "splitmask") {                                emit_csv(f, c "," (c + 1)) }
            else if (mode == "smt256") {
                if (f[4] == "dec0154") { f[4] = "dec0153"; f[5] = c + stride }
                emit_csv(f, c "," (c + stride))
            }
            else if (mode == "offset") {
                nc = c + 4
                if (nc > stride - 1) next
                f[5] = nc; f[6] = nc
                f[7] = int(nc / 64); f[8] = int(nc / 16); f[9] = int(nc / 8)
                emit_csv(f, nc "," (nc + stride))
            }
            next
        }

        { print }
    ' "${src}" > "${dst}"
    echo "wrote ${dst##*/}"
}

derive perthread_mpich.out  perthread
derive wholecore_mpich.out  wholecore
derive smt256_mpich.out     smt256
derive unbound_mpich.out    unbound
derive splitmask_mpich.out  splitmask
derive offset_mpich.out     offset

# The checker resolves topology.json from the directory of the report file, so
# the derived fixtures need their own copy for the tests to stay hermetic.
cp "${HERE}/../topology.json" "${HERE}/topology.json"
