"""jobfile -- write what one job is given, in the two forms it is needed in.

    job.env    flat `KEY='value'` lines.  What bench/runner.sh sources.
    job.json   the same facts structured.  What a reader and bench/collect use.
    job.pbs    the generated scheduler script, rendered from the site's job
               template -- sites/job.<scheduler>.tmpl, or sites/<site>/job.tmpl
               where a site needs directives of its own

THE JOB NEVER PARSES YAML

That is the whole reason this module exists.  Expanding the matrix on the host
and handing the job a flat file avoids YAML-in-bash entirely, and makes each
job's inputs an artifact you can read after the fact rather than something you
reconstruct from the submitter's arguments.

WHY THE SCHEDULER SCRIPT IS GENERATED RATHER THAN REUSED

Scheduler directives cannot be parameterised inside the file: `#PBS -l select=`
is a comment to the shell and a directive to PBS, and nothing expands a variable
in between.  The previous submitter fought that by overriding `-l select=` and
`-l walltime=` on the qsub line and smuggling the rest through
`-v NCAR_HPC_ROOT=...,container_img=...,RESULTS_DIR=...`.  Generating the script
puts the real directive in the file, drops the -v channel entirely, and leaves
behind the exact script that ran.  JUBE and Ramble both generate; it is the
right call.
"""

import datetime
import json
import os


def select_size(exp, job):
    """(ncpus, mpiprocs) for one node in the select directive.

    Exclusive by default, which asks for every core on the node whether or not
    this job's cells use them all.  For a benchmark that is the only defensible
    setting: a co-tenant's work on the same node lands in your timings as noise
    you cannot see, cannot subtract and will not know is there.  Paying for idle
    cores is the cheaper mistake.

    defaults.exclusive: false asks for exactly what the cells use.  That is for a
    machine whose nodes are shared by design -- Casper's high-throughput nodes
    are documented as being for tasks using one or two CPUs -- where holding a
    whole node means waiting for the scheduler to drain other people's small jobs
    from it.  It buys queue time and costs comparability, and it is the right
    trade only while the question is "does this harness run here at all".

    The exclusive answer is not simply the larger one.  It is a different claim:
    give me the node.  So the two are not max()ed together.
    """
    if exp.defaults["exclusive"]:
        return exp.site.cores_per_node, exp.site.cores_per_node
    ranks = max(c.placement["ranks_per_node"] for c in job.cells)
    cpus = max(c.placement["ranks_per_node"] * c.placement["threads"]
               for c in job.cells)
    return cpus, ranks


def render(template_path, values):
    """Substitute @NAME@ placeholders; refuse to leave one unfilled."""
    with open(template_path) as fh:
        text = fh.read()
    for key, value in values.items():
        text = text.replace("@%s@" % key, str(value))
    leftover = sorted({w.strip("@") for w in _placeholders(text)})
    if leftover:
        raise KeyError("%s has placeholders nothing filled: %s"
                       % (template_path, ", ".join(leftover)))
    return text


def _placeholders(text):
    out, i = [], 0
    while True:
        start = text.find("@", i)
        if start < 0:
            return out
        end = text.find("@", start + 1)
        if end < 0:
            return out
        word = text[start:end + 1]
        if word[1:-1].replace("_", "").isalnum() and word[1:-1].isupper():
            out.append(word)
        i = end + 1


def _sh(value):
    """Single-quote for bash.  Values come from a config file, not a person."""
    return "'" + str(value).replace("'", "'\\''") + "'"


def job_env(exp, job, results_dir, profile=None):
    lines = [
        "# job.env -- generated by bench/submit from %s" % exp.path,
        "#            on %s" % datetime.datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ"),
        "#",
        "# Sourced by bench/runner.sh.  This flat file IS the expanded",
        "# configuration: the job never reads the experiment YAML, and reading",
        "# this directory never requires it either.",
        "",
        "BENCH_SITE=%s" % _sh(exp.site.name),
        "BENCH_EXPERIMENT=%s" % _sh(exp.name),
        "BENCH_JOB_KEY=%s" % _sh(job.key),
        "BENCH_PROFILE=%s" % _sh(profile or ""),
        "BENCH_HARNESS=%s" % _sh(exp.site.bench_root),
        "",
        "RESULTS_DIR=%s" % _sh(results_dir),
        "container_img=%s" % _sh(exp.site.image_path(job.image)),
        "",
        "APP=%s" % _sh(job.app["name"]),
        "APP_ARGS=%s" % _sh(job.app.get("args", "")),
        "BENCH_SCALE=%s" % _sh(job.scale),
        "BENCH_TARGET_SECONDS=%s" % _sh(job.target_seconds),
        "BENCH_NODES=%s" % _sh(job.nodes),
        "BENCH_REPEATS=%s" % _sh(job.repeats),
        "BENCH_ALLOW_UNDERSUBSCRIBED=%s"
        % _sh("true" if exp.defaults["allow_undersubscribed"] else "false"),
    ]

    app_env = job.app.get("env") or {}
    if app_env:
        lines += ["",
                  "# The app's own environment.  Exported, because these have to",
                  "# reach the hooks INSIDE the container -- apptainer passes the",
                  "# host environment through, so exporting here is enough."]
        for key in sorted(app_env):
            lines.append("export %s=%s" % (key, _sh(app_env[key])))

    lines += ["",
              "# The cells this job iterates, in order.  One placement x OMP",
              "# variant each; repeats are a loop in the runner, not cells here.",
              "BENCH_CELL_COUNT=%s" % _sh(len(job.cells))]
    for i, cell in enumerate(job.cells):
        lines += [
            "BENCH_CELL_%d_NAME=%s" % (i, _sh(cell.name)),
            "BENCH_CELL_%d_RANKS_PER_NODE=%s" % (i, _sh(cell.placement["ranks_per_node"])),
            "BENCH_CELL_%d_THREADS=%s" % (i, _sh(cell.placement["threads"])),
            "BENCH_CELL_%d_OMP=%s" % (i, _sh(cell.omp["name"])),
            "BENCH_CELL_%d_OMP_PROC_BIND=%s" % (i, _sh(cell.omp.get("OMP_PROC_BIND", ""))),
            "BENCH_CELL_%d_OMP_PLACES=%s" % (i, _sh(cell.omp.get("OMP_PLACES", ""))),
        ]
    return "\n".join(lines) + "\n"


def job_record(exp, job, results_dir, profile=None):
    return {
        "schema": 1,
        "generated": datetime.datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ"),
        "experiment": {"name": exp.name, "path": os.path.abspath(exp.path)},
        "site": {"name": exp.site.name, "conf": exp.site.conf,
                 "cores_per_node": exp.site.cores_per_node,
                 "smt": exp.site.smt, "node_source": exp.site.node_source},
        "profile": profile,
        "job": {"key": job.key, "nodes": job.nodes, "walltime": job.walltime,
                "repeats": job.repeats, "results_dir": results_dir},
        "image": {"sif": job.image, "path": exp.site.image_path(job.image)},
        "app": {"name": job.app["name"],
                "label": job.app.get("label") or job.app["name"],
                "args": job.app.get("args", ""),
                "scale": job.scale, "target_seconds": job.target_seconds,
                "env": job.app.get("env") or {}},
        "cells": [{"name": c.name,
                   "ranks_per_node": c.placement["ranks_per_node"],
                   "threads": c.placement["threads"],
                   "omp": dict({"name": c.omp["name"]},
                               **{k: v for k, v in c.omp.items() if k != "name"})}
                  for c in job.cells],
    }


def write(exp, job, results_dir, template_path, account, profile=None):
    """Write job.env, job.json and job.pbs; return the job script's path."""
    if not os.path.isdir(results_dir):
        os.makedirs(results_dir)

    env_path = os.path.join(results_dir, "job.env")
    with open(env_path, "w") as fh:
        fh.write(job_env(exp, job, results_dir, profile))

    with open(os.path.join(results_dir, "job.json"), "w") as fh:
        json.dump(job_record(exp, job, results_dir, profile), fh,
                  indent=2, sort_keys=True)
        fh.write("\n")

    ncpus, mpiprocs = select_size(exp, job)
    script = render(template_path, {
        "JOB_NAME": "bench_" + job.key,
        "ACCOUNT": account,
        "QUEUE": exp.defaults["queue"],
        "WALLTIME": job.walltime,
        "NODES": job.nodes,
        "NCPUS": ncpus,
        "MPIPROCS": mpiprocs,
        # Already ':'-prefixed, or empty.  Appended to the select statement
        # rather than passed as a separate -l, because a resource that chooses
        # a node belongs to the chunk being described: `-l cpu_type=...` on its
        # own is a job-wide resource and does not mean the same thing.
        "NODE_SELECT": (":" + exp.site.node_select) if exp.site.node_select else "",
        "RESULTS_DIR": results_dir,
        "SITE_CONF": exp.site.conf,
        "BENCH_ROOT": exp.site.bench_root,
        "JOB_ENV": env_path,
        "EXPERIMENT": exp.path,
    })
    script_path = os.path.join(results_dir, "job.pbs")
    with open(script_path, "w") as fh:
        fh.write(script)
    os.chmod(script_path, 0o755)
    return script_path
